vocab_size: 32000
max_text_len: 512
max_seq_len: 708 #(max_text_len + (image_size//patch_size)**2)
d_model: 768
n_heads: 12
n_layers: 16
mlp_ratio: 4.0
dropout: 0.01
attn_dropout: 0.01
rope_theta: 10000.0
image_size: 224
patch_size: 16